FROM centos:latest
MAINTAINER Tim Kropp @sometheycallme

# install dependencies
RUN yum clean all && \
    yum -y install epel-release && \
    yum -y install PyYAML python-jinja2 python-httplib2 python-keyczar python-paramiko python-setuptools git python-pip

# install Bash Automated Testing Suite
RUN git clone git://github.com/sstephenson/bats.git /tmp/bats && \
    cd /tmp/bats && ./install.sh /usr/local && rm -rf /tmp/bats

# create path to Ansible working directory
RUN mkdir /etc/ansible/

# create seed host 
RUN echo "127.0.0.1" > /etc/ansible/inventory

# follow directions here
# for installation http://docs.ansible.com/ansible/intro_installation.html
RUN git clone http://github.com/ansible/ansible.git /opt/ansible/ansible
WORKDIR /opt/ansible/ansible
RUN git submodule update --init

# install GO Continous Delivery agent
# https://docs.go.cd/current/installation/install/agent/linux.html
RUN cd /tmp && curl -L -O http://download.go.cd/gocd-rpm/go-agent-16.3.0-3138.noarch.rpm
RUN yum -y localinstall /tmp/go-agent-16.3.0.3138.noarch.rpm
RUN rm -f /tmp/go-agent-16.3.0-3138.noarch.rpm
RUN sed -r -i "s/^(GO_SERVER)=(.*)/\1=\$SERVER_PORT_8153_TCP_ADDR/g" /etc/default/go-agent
VOLUME ["/var/lib/go-agent"]
CMD /usr/lib/jvm/jre-1.7.0-openjdk.x86_64/bin/java -jar /usr/share/go-agent/agent-bootstrapper.jar $SERVER_PORT_8153_TCP_ADDR $SERVER_PORT_8153_TCP_PORT

# create Ansible environment settings
ENV ANSIBLE_INVENTORY /etc/ansible/inventory
ENV PATH /opt/ansible/ansible/bin:/bin:/usr/bin:/sbin:/usr/sbin
ENV PYTHONPATH /opt/ansible/ansible/lib
ENV ANSIBLE_LIBRARY /opt/ansible/ansible/library
