FROM alpine:3.3
MAINTAINER Tim Kropp @sometheycallme

RUN apk upgrade --no-cache --available && \
    apk add --no-cache \
      python \
      python-pip \
      && pip install paramiko \
      && apk del --purge py-pip py-setuptools
