FROM alpine:3.4
MAINTAINER Tim Kropp @sometheycallme

COPY /fixtures/behave /tutorials

RUN apk upgrade --no-cache --available && \
    apk add --no-cache \
      bash \
      git \
      curl 
      py-pip \
      && pip install behave \
      && \
    :
