FROM alpine:3.4
MAINTAINER Tim Kropp @sometheycallme

RUN apk upgrade --no-cache --available && \
    apk add --no-cache \
      python \
      python-dev \
      gcc \
      py-pip \
      musl-dev \
      libffi-dev \
      bash \
      git \
      && pip install --upgrade pip \
      && pip install autostager \
      && \
    :
