FROM alpine:3.3
MAINTAINER Tim Kropp @sometheycallme

RUN apk upgrade --no-cache --available && \
    apk add --no-cache \
      python \
      py-pip \
      bash \i
      go \
      && \
    apk add --no-cache -X 'http://dl-cdn.alpinelinux.org/alpine/edge/main' \
      'ansible>=2.0' \
      && pip install --upgrade pip \
      && pip install boto \
      && go get github.com/bketelsen/captainhook \
    :

WORKDIR /opt/ansible

#ENTRYPOINT ["ansible"]
#CMD ["ansible --version"]
