FROM alpine:3.4
MAINTAINER Tim Kropp @sometheycallme

RUN apk upgrade --no-cache --available && \
    apk add --no-cache \
      python \
      python-dev \
      py-pip \ 	
      gcc \
      musl-dev \
      libffi-dev \
      openssl-dev \
      bash \
      git \
      && git clone https://github.com/jfach/autostager \
      && pip install --upgrade pip \
      && pip install --pre github3.py \
      && python setup.py autostager/setup.py \
      && \
    :
