FROM alpine:3.4
MAINTAINER Tim Kropp @sometheycallme

COPY /helpful_files /opt/client

RUN apk upgrade --no-cache --available && \
    apk add --no-cache \
      python \
      py-pip \
      bash \
      git \
      curl \
      && git clone https://github.com/cleanerbot/ansible-security \
      && git clone https://github.com/jorisroovers/gitlint \
      && pip install --upgrade pip \
      && pip install boto \
      && pip install requests \
      && pip install setuptools \
      && pip install wheel==0.24.0 \
      && pip install Click==5.1 \
      && pip install sh==1.11 \
      && pip install ordereddict==1.1 \
      && pip install importlib==1.0.3
      && cd gitlint; python setup.py develop \
      && \
    :

ENTRYPOINT ["gitlint --help"]
