FROM alpine:3.4
MAINTAINER Tim Kropp @sometheycallme

COPY /helpful_files /opt/client

RUN apk upgrade --no-cache --available && \
    apk add --no-cache \
      python \
      py-pip \
      bash \
      git \
      curl \
      && git clone https://github.com/cleanerbot/ansible-security \
      && git clone https://github.com/jorisroovers/gitlint.git \
      && pip install --upgrade pip \
      && pip install boto \
      && pip install requests \
      && pip install -r /jorisroovers/requirements.txt \
      && python /jorisroovers/setup.py develop \
      && \
    :

WORKDIR /ansible-security
ENTRYPOINT ["gitlint --help"]
