FROM python:2.7-alpine
# https://github.com/docker-library/python/blob/master/2.7/Dockerfile
MAINTAINER Tim Kropp @sometheycallme

RUN apk upgrade --no-cache --available && \
    apk add --no-cache \
      bash \
      git \
      curl \
      && pip install pyyaml==3.11 \
      && pip install c7n \
      && \
    :

VOLUME ["/var/log/cloud-custodian", "/etc/cloud-custodian"]
ENTRYPOINT ["/usr/local/bin/custodian"]
