FROM alpine:3.4
MAINTAINER Tim Kropp @sometheycallme
ENV GOPATH=$HOME/go
# https://github.com/opencontrol/compliance-masonry/blob/master/docs/development.md

RUN apk upgrade --no-cache --available && \
    apk add --no-cache \
      go \
      bash \
      git \
      curl \ 
      && go get github.com/opencontrol/compliance-masonry \
      && curl https://glide.sh/get | sh \
      && glide up --all-dependencies \
      && \
    :

#ENTRYPOINT ["compliance-masonry"]
