#!/bin/bash
set -e

options="--rm"
echo $@ | grep '\--no-cache' &> /dev/null && options="$options --no-cache" || :

echo "Building the Ansible Control image"
docker build --rm -t ~/ansible-security/Docker/Dockerfile

echo "Show image sizes."
docker images | egrep '^ansible\b' | sort

echo
echo "WARN: you should docker tag the ansible control host image."
echo
