#!/bin/bash
set -e

. script/options.bash

options="--rm"
echo $@ | grep '\--no-cache' &> /dev/null && options="$options --no-cache" || :

echo "Building the Ansible Control image"
docker build $options -f dockerfiles/dockerfile-ansible -t ${LOCAL_IMAGE} .

echo "Show image sizes."
docker images | grep ansible-security | sort

echo
echo "WARN: you should docker tag the ansible control host image."
echo
