#!/bin/bash

. script/options.bash

#!/bin/bash

set -o errexit

docker ps -a
docker images

echo "==========================================="
echo "List images and PIDS                       "
echo "==========================================="
