#!/bin/bash
set -e

. script/options.bash

docker login -e ${mail} -u ${user} -p ${pass}
docker tag ${IMAGE_NAME_TAG} sometheycallme/ansible-controller:latest
docker push sometheycallme/ansible-controller:latest
docker logout
