#!/bin/bash
set -ex -o pipefail
. script/options.bash

echo "Step1: Test for basic ansible install"
docker run --volumes-from ${DATA_IMAGE} -t -i --entrypoint bash ${CONTROLLER_IMAGE} -c "ls /opt/ansible" | grep ansible

echo "Step2: Test for fixtures volume"
docker run --volumes-from playbooks-data:latest -t -i --entrypoint bash ${CONTROLLER_IMAGE} -c "ls /opt" | grep staging
